-- vim.g.rustaceanvim = {
--   -- Plugin configuration
--   tools = {
--   },
--   -- LSP configuration
--   server = {
--     on_attach = function(client, bufnr)
--         client.server_capabilities.semanticTokensProvider = nil
--     end,
--     default_settings = {
--       -- rust-analyzer language server configuration
--       ['rust-analyzer'] = {
--       },
--     },
--   },
--   -- DAP configuration
--   dap = {
--   },
-- }
