require("which-key").setup({
    preset = "helix",
    delay = 0,
    spec = {
        mode = { "n", "v" },
        { "g", group = "goto" },
        { "]", group = "next" },
        { "[", group = "prev" },
        -- {"<leader><tab>" = { group = "tabs" },
        { "<leader>b", group = "buffer" },
        { "<leader>c", group = "code" },
        { "<leader>f", group = "file/find" },
        { "<leader>fg", group = "Git" },
        -- ["<leader>g"], group = "+git" },
        { "<leader>gh", group = "hunks" },
        { "<leader>m", group = "music" },
        -- {"<leader>l", group = "lsp" },
        -- {"<leader>q", group = "quit/session" },
        -- {"<leader>s", group = "search" },
        -- {"<leader>t", group = "testing" },
        -- {"<leader>u", group = "ui" },
        { "<leader>w", group = "windows" },
        { "<leader>x", group = "delete" },
    },
})
